.TH HEADCRITD 8
.SH NAME
headcritd \- a service that does nothing useful
.SH SYNOPSIS
.B headcritd
[\fB\-\-help\fR]
[\fB\-\-config\fR \fIFILE\fR]
.SH DESCRIPTION
.B headcritd
is an example daemon that does nothing of particular use other than serve as 
an example of a how to implement a basic daemon in Linux.
.SH OPTIONS
.TP
.BR \-\-help
Print a usage message an exit.
.TP
.BR \-\-config " " \fIFILE\fR
A configuration file.
.SH NOTES
TBA
.SH BUGS
TBA
.SH SEE ALSO
TBA
