.TH LETTERS-TO-NUMBERS 1 October 2024 "Utility Commands"
.SH NAME
letters-to-numbers \- converts a string into a series of digits
.SH SYNOPSIS
.B letters-to-numbers
\fISTRING\fR ...
.SH DESCRIPTION
.B letters-to-numbers
converts strings of characters from the command line into strings of digits.
It prints the string both the full number of the letter in the alphabet and
with the tens digit removed.
.SH EXIT STATUS
Returns zero if if the input is successfully converted.
Returns 1 on any error.
.TH BUGS
Depends upon the expectations of the user.

